# Generated by Django 5.0.3 on 2024-04-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrosABM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.AddField(
            model_name='persona',
            name='dni_pasaporte',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_habitacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
